env:
  browser: true
  es6: true
extends: 'eslint:recommended'
globals:
  chrome: false
rules:
  indent:
    - error
    - 2
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - single
  semi:
    - error
    - always
