env:
  es6: true
  browser: true
  node: true
extends: 'eslint:recommended'
globals:
  chrome: false
rules:
  indent:
    - error
    - 2
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - single
  semi:
    - error
    - always
overrides:
  - files:
      - '**/*.test.js'
    env:
      jest: true
